name: Continuous Integration (CI)

on: pull_request

env:
  # Forcing Earthly to use colours, to make reading output easier.
  FORCE_COLOR: 1

jobs:
  go-formatting:
    name: Go Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check Go formatting.
        run: earthly --ci +check-go-formatting
  shell-formatting:
    name: Shell Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check Shell formatting.
        run: earthly --ci +check-shell-formatting
  yaml-formatting:
    name: YAML Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check YAML formatting.
        run: earthly --ci +check-yaml-formatting
  go-linting:
    name: Go Linting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check Go linting.
        run: earthly --ci +check-go-linting
  shell-linting:
    name: Shell Linting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check Shell linting.
        run: earthly --ci +check-shell-linting
  modules:
    name: Modules
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check modules.
        run: earthly --ci +check-modules
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Compile.
        run: earthly --ci +compile
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.6.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Unit test.
        run: earthly --ci +unit-test
