name: Mirror to GitLab

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push To Gitlab
      env:
        token: ${{ secrets.GITLAB_PERSONAL_ACCESS_TOKEN }}
      run: |
        git remote set-url origin "https://oauth2:${token}@gitlab.com/DeveloperC/starlingbanktechnicalchallenge"
        git push
