name: Mirroring

on: [create, push, delete]

jobs:
  GitLab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirroring
        run: git push --mirror "https://oauth2:${{ secrets.GITLAB_PERSONAL_ACCESS_TOKEN }}@gitlab.com/DeveloperC/starlingbanktechnicalchallenge"
