name: Releasing

on:
  push:
    branches: [main]

env:
  # Forcing Earthly to use colours, to make reading output easier.
  FORCE_COLOR: 1

permissions:
  # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  # `write` allows GitHub Actions to create a release.
  contents: write

jobs:
  Releasing:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.12.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.12/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Releasing.
        run: earthly --ci --secret GH_TOKEN +releasing
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by GitHub Actions.
